### ISSUE TITLE
Tag Editor 

### ISSUE THREAD

**Issue by joebentaylor1995** [datocms/plugins#33]
Hey, so the output from GraphQL is something like:

```
"[\n  \"Print\",\n  \"Branding\",\n  \"Web Design\",\n  \"Development\"\n]"
```

How do I turn this into an array with strings? Like:

```
[
  'Print',
  'Branding',
  'Web Design',
  'Development',
]
```

**Comment by stefanoverna** [comment]
Hi Joe! 



Thank you for reporting this. We will take a look and get back to you shortly!


Best,

—
Stefano Verna
Founder and CEO
DatoCMS

--- original message ---
On June 14, 2021, 4:35 AM GMT+2 ***@***.*** wrote:



Hey, so the output from GraphQL is something like:

"[\n \"Print\",\n \"Branding\",\n \"Web Design\",\n \"Development\"\n]"

How do I turn this into an array with strings? Like:

[
'Print',
'Branding',
'Web Design',
'Development',
]

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by joebentaylor1995** [comment]
Found the fix through a helpful comment in stack overflow (this should be updated in the plguin docs...)

```
str = "[\n  \"Print\",\n  \"Branding\",\n  \"Web Design\",\n  \"Development\"\n]";

JSON.parse(str);
```

**Comment by souljuse** [comment]
Hi @joebentaylor1995! Are you using Gatsby?

**Comment by souljuse** [comment]
Just to clarify, Gatsby GraphQL API fetches data from DatoCMS using our REST API, and probably it is why the JSON you receive in Gatsby is stringified.

DatoCMS GraphQL API returns a JSON object.
