### ISSUE TITLE
Usage with modular field

### ISSUE THREAD

**Issue by kokarn** [datocms/plugins#5]
Hey!

I have a model (market) that I would like to display linked "kits" for.

However, the structure of the kit means the link back to market is from kit->modularField->market.

Is it possible for me to display those posts or is that kind of structure a limitation in the plugin?

**Comment by matjack1** [comment]
Hey @kokarn sorry for the delay in getting back to you, of which plugin are you talking about sorry?

**Comment by kokarn** [comment]
I'm actually not sure anymore, but I believe it's for this https://github.com/datocms/plugins/tree/master/inverse-relationships

**Comment by matjack1** [comment]
It looks broken to me. Thank you for your report! We'll have a look as soon as possible

**Comment by matjack1** [comment]
Actually, I don't know what happened last time but it's working fine the normal plugin.

Your use case instead is not supported, I'll leave the issue here as a feature request (or if you want you can try hacking your way here: https://github.com/datocms/plugins/blob/master/inverse-relationships/src/index.js :)

**Comment by matjack1** [comment]
I'm closing this to move all the feature requests here: https://community.datocms.com/t/inverse-relationships-plugin-with-modular-field/450
